// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      print("heeloo");
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4FBu_DqryPCKixbMqbarvJU9maLB-vVY',
    appId: '1:178371786788:web:79dea8c292c77819b280b1',
    messagingSenderId: '178371786788',
    projectId: 'health-broo',
    databaseURL: 'https://health-broo-default-rtdb.asia-southeast1.firebasedatabase.app/',
    
    authDomain: 'health-broo.firebaseapp.com',
    storageBucket: 'health-broo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRPckyD8baxXQ9K9HAHLFP8oODOk8Ihqs',
    appId: '1:178371786788:android:f95b394a9193acd1b280b1',
    messagingSenderId: '178371786788',
    projectId: 'health-broo',
    databaseURL: 'https://health-broo-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'health-broo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB35YSB3fqjU1EWQSG7bi55ves1sdEQjm4',
    appId: '1:178371786788:ios:8c8b02330f249678b280b1',
    messagingSenderId: '178371786788',
    projectId: 'health-broo',
    storageBucket: 'health-broo.firebasestorage.app',
    iosBundleId: 'com.example.healthBroo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB35YSB3fqjU1EWQSG7bi55ves1sdEQjm4',
    appId: '1:178371786788:ios:8c8b02330f249678b280b1',
    messagingSenderId: '178371786788',
    projectId: 'health-broo',
    storageBucket: 'health-broo.firebasestorage.app',
    iosBundleId: 'com.example.healthBroo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4FBu_DqryPCKixbMqbarvJU9maLB-vVY',
    appId: '1:178371786788:web:d9fad053acef16b4b280b1',
    messagingSenderId: '178371786788',
    projectId: 'health-broo',
    authDomain: 'health-broo.firebaseapp.com',
    storageBucket: 'health-broo.firebasestorage.app',
  );
}
