name: Manually Release Flutter APK

on:
  workflow_dispatch:  # Manual trigger from GitHub UI
    inputs:
      version:
        description: 'Release version (e.g. v1.0.0)'
        required: true
      release_notes:
        description: 'Release notes'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      # Get dependencies
      - name: Install dependencies
        run: flutter pub get

      
      # Build release APK
      - name: Build signed release APK
        run: flutter build apk --release

      # Upload APK to GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.release_notes }}
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
